#!/usr/bin/env python3
"""Render all curated registries; --check makes generated-file drift fail CI."""
import argparse
import hashlib
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROTOCOL_FIELDS = ('dataset_id', 'split_identity', 'split', 'training_regime', 'setting', 'features',
                   'sampling', 'segmentation', 'shot_aggregation', 'budget', 'solver',
                   'reference_aggregation', 'metric', 'unit', 'runs', 'variance', 'reproduction')


def read_records(name):
    paths = sorted((ROOT / 'data/papers').glob('*.json')) if name == 'papers' else [ROOT / f'data/{name}.json']
    return [record for path in paths for record in json.loads(path.read_text(), parse_constant=lambda value: (_ for _ in ()).throw(ValueError('Nonfinite JSON constant: ' + value)))]


def cell(value):
    if isinstance(value, list):
        value = '; '.join(value) or 'None'
    return str(value).replace('|', '&#124;').replace('\n', ' ')


def protocol_key(record):
    # An unknown value cannot establish compatibility, even with another unknown.
    values = tuple(record[k] for k in PROTOCOL_FIELDS)
    if any(any(marker in value.lower() for marker in ('not reported', 'not independently verified', 'unknown', 'unspecified')) for value in values):
        return values + (record['id'],)
    return values


def render():
    files = {}
    for kind, title, name_key in [('papers', 'Paper catalog', 'title'), ('datasets', 'Dataset catalog', 'name'), ('resources', 'Code and learning resource catalog', 'name')]:
        records = sorted(read_records(kind), key=lambda r: (r.get('year', 0), r['id']))
        out = [f'# {title}', '', '<!-- Generated by scripts/generate_catalog.py; edit data/ instead. -->', '',
               '[Handbook home](../../README.md) · [Coverage methodology](../15-coverage.md)', '',
               f'{len(records)} records. Verification is field-specific; source inspection does not certify runtime reproduction.', '']
        if kind == 'papers':
            out += ['| Paper | Year / venue | Supervision | Code |', '|---|---|---|---|']
            for r in records:
                code = f"[source]({r['code_url']})" if r['code_url'].startswith('https://') else cell(r['code_url'])
                out.append(f"| [{cell(r['title'])}](#{r['id']}) | {r['year']} / {cell(r['venue'])} | {cell(r['supervision'])} | {code} |")
            out += ['']
        for r in records:
            out += [f"<a id=\"{r['id']}\"></a>", '', f"## {cell(r[name_key])}", '']
            for key, value in r.items():
                if key in ('id', name_key):
                    continue
                display = cell(value)
                if key.endswith('_url') or key == 'url':
                    display = f'[{key.replace("_", " ")}]({value})' if value.startswith('https://') else display
                if key == 'sources':
                    display = ' · '.join(f'[source {i}]({u})' for i, u in enumerate(value, 1))
                out += [f'- **{key.replace("_", " ").capitalize()}:** {display}']
            out += ['']
        files[ROOT / f'docs/generated/{kind}.md'] = '\n'.join(out)
    groups = defaultdict(list)
    results = read_records('results')
    for record in results:
        groups[protocol_key(record)].append(record)
    out = ['# Protocol-separated benchmarks', '', '<!-- Generated by scripts/generate_catalog.py; edit data/results.json instead. -->', '',
           '[Handbook home](../README.md) · [Metric definitions](02-evaluation.md) · [Paper catalog](generated/papers.md)', '',
           f'{len(results)} primary-source result records; {len(groups)} exact protocol groups. All values retain author/reproduction status.', '',
           'Groups require equality of the full recorded protocol tuple. Unknown metadata isolates a record. A missing split identity isolates a record even when prose such as “random 80/20” matches. An identity must name a verified shared split artifact, fixed official partition, or primary experiment configuration; comparison notes remain binding. No global SOTA ranking is asserted; the highest value within a multi-row group is only the best value in this catalog under that recorded protocol, not a verified field-wide best.', '']
    for key, rows in sorted(groups.items(), key=lambda item: (item[1][0]['dataset'], item[1][0]['setting'], item[1][0]['id'])):
        r = rows[0]
        digest = hashlib.sha256(json.dumps(key).encode()).hexdigest()[:8]
        out += [f"## {r['dataset']} — {r['setting']} — {r['metric']} ({digest})", '',
                '| Method | Value | Runs / uncertainty | Source |', '|---|---:|---|---|']
        for r in rows:
            out += [f"| [{cell(r['method'])}](generated/papers.md#{r['paper_id']}) | {r['value']:g} {cell(r['unit'])} | {cell(r['runs'])}; {cell(r['variance'])} | [{cell(r['source_location'])}]({r['source_url']}) |"]
        out += ['', '<details>', '<summary>Full protocol and comparison limits</summary>', '']
        for field in PROTOCOL_FIELDS:
            out += [f'- **{field.replace("_", " ").capitalize()}:** {cell(rows[0][field])}']
        for r in rows:
            out += [f"- **{r['id']} ({r['verified_on']}):** {cell(r['comparability_notes'])}"]
        out += ['', '</details>', '']
    files[ROOT / 'docs/12-benchmarks.md'] = '\n'.join(out)
    return files


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for path, text in render().items():
        text = text.rstrip() + '\n'
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    if stale:
        raise SystemExit('STALE: ' + ', '.join(stale))
    print('PASS: 4 generated catalogs are current' if args.check else 'Generated 4 catalogs')


if __name__ == '__main__':
    main()
